with open('input1.txt') as input_file:
    content=input_file.read()
    modified_content=content.upper().replace('SMART','Genius')
    print(modified_content)

#1.CISCO SERVICE:TECHNICAL SERVICES:Genius SERVICES TECHNOLOGY GROUP SSTG:CMS:QS EM7:EM7 HSBC RBA USER
#2.CISCO SERVICE:TECHNICAL SERVICES:Genius SERVICES TECHNOLOGY GROUP SSTG:CMS:CISCO MANAGED SERVICES -SERVICENOW ACCESS:CMS-DOMAIN-PLATFORM-OPERATIONS-ROLE
#3.CISCO SERVICE:TECHNICAL SERVICES:Genius SERVICES TECHNOLOGY GROUP SSTG:CMS:CMS SERVICE NOW - ASSIGNMENT GROUPS:CMS-AG-UC-DEFAULT
#4.CISCO SERVICE:TECHNICAL SERVICES:Genius SERVICES TECHNOLOGY GROUP SSTG:CMS:CISCO MANAGED SERVICES -SERVICENOW ACCESS:CMS-PLATOPS-PORTAL

with open('output1.txt','w') as output_file:
    output_file.write(modified_content)

input_file.close()
output_file.close()
